defaults: &defaults
  docker:
    - image: circleci/node:10

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Download, install and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Run tests!
      - run: yarn run test-ci

  build:
    <<: *defaults
    steps:
      - checkout

      # Download, install and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn && yarn update-translations:build && yarn update-translations && yarn build

  deploy:
    <<: *defaults
    steps:
      - checkout

      # Download, install and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn && yarn deploy

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
