// @flow

export const data = {
  shoppingOnTheGo: [
    {
      id: 1,
      imageUrl: "/static/images/itinerary/shopping/explore-the-souks.jpg",
      time: "8 AM",
      title: "shoppingOnTheGo__exploreTheSouksTitle",
      description: "shoppingOnTheGo__exploreTheSouksDescription",
    },
    {
      id: 2,
      imageUrl: "/static/images/itinerary/shopping/visit-the-dubai-mall.jpg",
      time: "10 AM",
      title: "shoppingOnTheGo__visitTheMallTitle",
      description: "shoppingOnTheGo__visitTheMallDescription",
    },
    {
      id: 3,
      imageUrl: "/static/images/itinerary/shopping/shop-til-you-drop.jpg",
      time: "11 AM",
      title: "shoppingOnTheGo__ShopTilYouDropTitle",
      description: "shoppingOnTheGo__ShopTilYouDropDescription",
    },
    {
      id: 4,
      imageUrl: "/static/images/itinerary/shopping/mingle-with-the-locals.jpg",
      time: "1 PM",
      title: "shoppingOnTheGo__mingleWithTheLocalsTitle",
      description: "shoppingOnTheGo__mingleWithTheLocalsDescription",
    },
    {
      id: 5,
      imageUrl: "/static/images/itinerary/shopping/epic-entertainment.jpg",
      time: "3 PM",
      title: "shoppingOnTheGo__epicEntertainmentTitle",
      description: "shoppingOnTheGo__epicEntertainmentDescription",
    },
    {
      id: 6,
      imageUrl: "/static/images/itinerary/shopping/chill-at-the-beach.jpg",
      time: "4 PM",
      title: "shoppingOnTheGo__chillAtTheBeachTitle",
      description: "shoppingOnTheGo__chillAtTheBeachDescription",
    },
    {
      id: 7,
      imageUrl: "/static/images/itinerary/shopping/finish-with-a-thrill.jpg",
      time: "7 PM",
      title: "shoppingOnTheGo__finishWithAThrillTitle",
      description: "shoppingOnTheGo__finishWithAThrillDescription",
    },
  ],
  coloursSoundsFlavours: [
    {
      id: 1,
      imageUrl: "/static/images/itinerary/flavours/get-on-the-water.jpg",
      time: "8 AM",
      title: "coloursSoundsFlavours__getOnTheWaterTitle",
      description: "coloursSoundsFlavours__getOnTheWaterDescription",
    },
    {
      id: 2,
      imageUrl: "/static/images/itinerary/flavours/a-feast-for-foodies.jpg",
      time: "10 AM",
      title: "coloursSoundsFlavours__aFeastForFoodiesTitle",
      description: "coloursSoundsFlavours__aFeastForFoodiesDescription",
    },
    {
      id: 3,
      imageUrl: "/static/images/itinerary/flavours/understand-the-culture.jpg",
      time: "11 AM",
      title: "coloursSoundsFlavours__understandTheCultureTitle",
      description: "coloursSoundsFlavours__understandTheCultureDescription",
    },
    {
      id: 4,
      imageUrl: "/static/images/itinerary/flavours/explore-the-souks.jpg",
      time: "1 PM",
      title: "coloursSoundsFlavours__exploreTheSouksTitle",
      description: "coloursSoundsFlavours__exploreTheSouksDescription",
    },
    {
      id: 5,
      imageUrl: "/static/images/itinerary/flavours/learn-the-history.jpg",
      time: "3 PM",
      title: "coloursSoundsFlavours__learnTheHistoryTitle",
      description: "coloursSoundsFlavours__learnTheHistoryDescription",
    },
    {
      id: 6,
      imageUrl: "/static/images/itinerary/flavours/fabulous-flowers.jpg",
      time: "4 PM",
      title: "coloursSoundsFlavours__fabulousFlowersTitle",
      description: "coloursSoundsFlavours__fabulousFlowersDescription",
    },
    {
      id: 7,
      imageUrl: "/static/images/itinerary/flavours/the-art-of-water.jpg",
      time: "7 PM",
      title: "coloursSoundsFlavours__theArtOfWaterTitle",
      description: "coloursSoundsFlavours__theArtOfWaterDescription",
    },
  ],
  familyFun: [
    {
      id: 1,
      imageUrl: "/static/images/itinerary/family/splash-tacular.jpg",
      time: "8 AM",
      title: "familyFun__splashTacularTitle",
      description: "familyFun__splashTacularDescription",
    },
    {
      id: 2,
      imageUrl: "/static/images/itinerary/family/creatures-of-the-deep.jpg",
      time: "10 AM",
      title: "familyFun__creaturesOfTheDeepTitle",
      description: "familyFun__creaturesOfTheDeepDescription",
    },
    {
      id: 3,
      imageUrl: "/static/images/itinerary/family/ski-and-skate.jpg",
      time: "11 AM",
      title: "familyFun__skiAndSkateTitle",
      description: "familyFun__skiAndSkateDescription",
    },
    {
      id: 4,
      imageUrl: "/static/images/itinerary/family/desert-adventures.jpg",
      time: "1 PM",
      title: "familyFun__desertAdventuresTitle",
      description: "familyFun__desertAdventuresDescription",
    },
    {
      id: 5,
      imageUrl: "/static/images/itinerary/family/rollercoaster-mayhem.jpg",
      time: "3 PM",
      title: "familyFun__rollercoasterMayhemTitle",
      description: "familyFun__rollercoasterMayhemDescription",
    },
    {
      id: 6,
      imageUrl: "/static/images/itinerary/family/put-the-kids-in-charge.jpg",
      time: "4 PM",
      title: "familyFun__putTheKidsInChargeTitle",
      description: "familyFun__putTheKidsInChargeDescription",
    },
    {
      id: 7,
      imageUrl: "/static/images/itinerary/family/pedal-to-the-metal.jpg",
      time: "7 PM",
      title: "familyFun__pedalToTheMetalTitle",
      description: "familyFun__pedalToTheMetalDescription",
    },
  ],
  likeCelebrity: [
    {
      id: 1,
      imageUrl: "/static/images/itinerary/celebrity/champagne-brunch.jpg",
      time: "8 AM",
      title: "likeCelebrity__champagneBrunchTitle",
      description: "likeCelebrity__champagneBrunchDescription",
    },
    {
      id: 2,
      imageUrl: "/static/images/itinerary/celebrity/go-for-gold.jpg",
      time: "10 AM",
      title: "likeCelebrity__goForGoldTitle",
      description: "likeCelebrity__goForGoldDescription",
    },
    {
      id: 3,
      imageUrl: "/static/images/itinerary/celebrity/relax-in-the-sun.jpg",
      time: "11 AM",
      title: "likeCelebrity__relaxInTheSunTitle",
      description: "likeCelebrity__relaxInTheSunDescription",
    },
    {
      id: 4,
      imageUrl: "/static/images/itinerary/celebrity/pamper-yourself.jpg",
      time: "1 PM",
      title: "likeCelebrity__pamperYourselfTitle",
      description: "likeCelebrity__pamperYourselfDescription",
    },
    {
      id: 5,
      imageUrl: "/static/images/itinerary/celebrity/explore-the-jbr.jpg",
      time: "3 PM",
      title: "likeCelebrity__exploreTheJBRTitle",
      description: "likeCelebrity__exploreTheJBRDescription",
    },
    {
      id: 6,
      imageUrl: "/static/images/itinerary/celebrity/shop-til-you-drop.jpg",
      time: "4 PM",
      title: "likeCelebrity__ShopTilYouDropTitle",
      description: "likeCelebrity__ShopTilYouDropDescription",
    },
    {
      id: 7,
      imageUrl: "/static/images/itinerary/celebrity/a-view-like-no-other.jpg",
      time: "7 PM",
      title: "likeCelebrity__aViewLikeNoOtherTitle",
      description: "likeCelebrity__aViewLikeNoOtherDescription",
    },
  ],
  sizeIsEverything: [
    {
      id: 1,
      imageUrl: "/static/images/itinerary/size/fabulous-fountains.jpg",
      time: "8 AM",
      title: "sizeIsEverything__fabulousFountainsTitle",
      description: "sizeIsEverything__fabulousFountainsDescription",
    },
    {
      id: 2,
      imageUrl: "/static/images/itinerary/size/elevator-to-the-skies.jpg",
      time: "10 AM",
      title: "sizeIsEverything__elevatorToTheSkiesTitle",
      description: "sizeIsEverything__elevatorToTheSkiesDescription",
    },
    {
      id: 3,
      imageUrl: "/static/images/itinerary/size/a-new-angle.jpg",
      time: "11 AM",
      title: "sizeIsEverything__aNewAngleTitle",
      description: "sizeIsEverything__aNewAngleDescription",
    },
    {
      id: 4,
      imageUrl: "/static/images/itinerary/size/shopping-with-a-twist.jpg",
      time: "1 PM",
      title: "sizeIsEverything__shoppingWithTwistTitle",
      description: "sizeIsEverything__shoppingWithTwistDescription",
    },
    {
      id: 5,
      imageUrl: "/static/images/itinerary/size/nothing-but-flowers.jpg",
      time: "3 PM",
      title: "sizeIsEverything__nothingButFlowersTitle",
      description: "sizeIsEverything__nothingButFlowersDescription",
    },
    {
      id: 6,
      imageUrl: "/static/images/itinerary/size/picture-this.jpg",
      time: "4 PM",
      title: "sizeIsEverything__pictureThisTitle",
      description: "sizeIsEverything__pictureThisDescription",
    },
    {
      id: 7,
      imageUrl: "/static/images/itinerary/size/endless-thrills.jpg",
      time: "7 PM",
      title: "sizeIsEverything__endlessThrillsTitle",
      description: "sizeIsEverything__endlessThrillsDescription",
    },
  ],
};

export const dropdownData = [
  {
    id: 1,
    value: "shoppingOnTheGo",
    label: "shoppingOnTheGo",
  },
  {
    id: 2,
    value: "coloursSoundsFlavours",
    label: "coloursSoundsFlavours",
  },
  {
    id: 3,
    value: "familyFun",
    label: "familyFun",
  },
  {
    id: 4,
    value: "likeCelebrity",
    label: "likeCelebrity",
  },
  {
    id: 5,
    value: "sizeIsEverything",
    label: "sizeIsEverything",
  },
];
